//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class email
    {
        public int id { get; set; }
        public Nullable<int> person_id { get; set; }
        public string email_type { get; set; }
        public string email1 { get; set; }
        public int active { get; set; }
    }
}
