//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string middlename { get; set; }
        public string company { get; set; }
        public string departments { get; set; }
        public string position { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string img { get; set; }
        public int active { get; set; }
        public Nullable<int> role_id { get; set; }
        public string information { get; set; }
        public string helpers { get; set; }
    }
}
